//! Ticket detail: the side peek and the full view (Linear's issue view,
//! with Jira's activity tabs). Read-only: body markdown renders with the
//! kit's TextView, checkbox runs show as sub-task rows with their progress.

use std::path::{Path, PathBuf};

use gpui_kit::assets::IconName;
use gpui_kit::component::button::{Button, ButtonVariants as _, DropdownButton};
use gpui_kit::component::menu::{DropdownMenu as _, PopupMenu, PopupMenuItem};
use gpui_kit::component::text::{TextView, TextViewState, TextViewStyle};
use gpui_kit::component::theme::ActiveTheme as _;
use gpui_kit::component::{Icon, Sizable as _};
use gpui_kit::prelude::FluentBuilder as _;
use gpui_kit::*;

use crate::app::{KuzgunApp, KuzgunHandle, ago_label, now_unix, with_app, zrem};
use crate::board::status_label;
use crate::git::History;
use crate::icons;
use crate::model::{self, Category, CheckItem, Mode};

/// The line the triage skill puts at the top of its comments.
const AI_MARK: &str = "This was generated by AI during triage";

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ActivityTab {
    All,
    Comments,
    History,
}

pub enum Block {
    Md(Entity<TextViewState>),
    Checks(Vec<CheckItem>),
}

pub struct CommentEntry {
    pub author: String,
    pub when: String,
    pub ai: bool,
    pub body: Entity<TextViewState>,
}

pub struct Detail {
    pub path: PathBuf,
    pub is_doc: bool,
    pub full: bool,
    source: String,
    blocks: Vec<Block>,
    comments: Vec<CommentEntry>,
    pub history: Option<History>,
    pub tab: ActivityTab,
    scroll: ScrollHandle,
    _history_task: Option<Task<()>>,
}

impl Detail {
    pub fn open(path: PathBuf, is_doc: bool, full: bool, app: &KuzgunApp, cx: &mut Context<KuzgunApp>) -> Self {
        let source = source_of(app, &path);
        let mut d = Self {
            path,
            is_doc,
            full,
            source: String::new(),
            blocks: Vec::new(),
            comments: Vec::new(),
            history: None,
            tab: ActivityTab::All,
            scroll: ScrollHandle::new(),
            _history_task: None,
        };
        d.rebuild(&source, cx);
        d.load_history(cx);
        d
    }

    /// After a reload: rebuild when the file changed, refresh history.
    pub fn refresh(&mut self, app: &KuzgunApp, cx: &mut Context<KuzgunApp>) {
        let now = source_of(app, &self.path);
        if now != self.source {
            self.rebuild(&now, cx);
            self.load_history(cx);
        }
    }

    fn load_history(&mut self, cx: &mut Context<KuzgunApp>) {
        let p = self.path.clone();
        self._history_task = Some(cx.spawn(async move |this, cx| {
            let q = p.clone();
            let h = cx.background_spawn(async move { crate::git::history(&q) }).await;
            let _ = this.update(cx, |this, cx| {
                if let Some(d) = &mut this.detail
                    && d.path == p
                {
                    d.history = Some(h);
                    cx.notify();
                }
            });
        }));
    }

    fn rebuild(&mut self, text: &str, cx: &mut Context<KuzgunApp>) {
        self.source = text.to_string();
        let (blocks, comments) = split_body(text, self.is_doc);
        self.blocks = blocks
            .into_iter()
            .map(|b| match b {
                RawBlock::Md(s) => Block::Md(cx.new(|cx| TextViewState::markdown(&s, cx))),
                RawBlock::Checks(c) => Block::Checks(c),
            })
            .collect();
        self.comments = comments
            .into_iter()
            .map(|(author, when, body)| {
                let ai = body.contains(AI_MARK);
                let body = body
                    .lines()
                    .filter(|l| !l.contains(AI_MARK))
                    .collect::<Vec<_>>()
                    .join("\n");
                CommentEntry {
                    author,
                    when,
                    ai,
                    body: cx.new(|cx| TextViewState::markdown(body.trim(), cx)),
                }
            })
            .collect();
    }
}

fn source_of(app: &KuzgunApp, path: &Path) -> String {
    app.board
        .find_path(path)
        .map(|ix| app.board.tickets[ix].raw.clone())
        .or_else(|| std::fs::read_to_string(path).ok())
        .unwrap_or_default()
}

enum RawBlock {
    Md(String),
    Checks(Vec<CheckItem>),
}

/// The body in display blocks (without H1, front matter, panel property
/// lines and the Comments section) and the parsed comments.
fn split_body(text: &str, is_doc: bool) -> (Vec<RawBlock>, Vec<(String, String, String)>) {
    let (_, start) = model::front_matter(text);
    let skip: Vec<usize> = if is_doc {
        Vec::new()
    } else {
        model::header_lines(text)
            .into_iter()
            .filter(|(_, k, _, _)| model::PANEL_KEYS.contains(&k.to_lowercase().as_str()))
            .map(|(i, _, _, _)| i)
            .collect()
    };
    let check = regex::Regex::new(r"^(\s*)[-*+] \[( |x|X)\] (.*)$").unwrap();
    let mut blocks = Vec::new();
    let mut md = String::new();
    let mut checks: Vec<CheckItem> = Vec::new();
    let mut comments_raw: Option<Vec<&str>> = None;
    let mut comments_done: Vec<&str> = Vec::new();
    let mut skipped_h1 = false;
    let mut in_fence = false;
    let lines: Vec<&str> = text.lines().collect();
    for (i, line) in lines.iter().enumerate().skip(start) {
        if let Some(c) = comments_raw.as_mut() {
            if line.starts_with("## ") {
                // A section after Comments goes back to the body.
                comments_done.append(c);
                comments_raw = None;
            } else {
                c.push(line);
                continue;
            }
        }
        if line.trim_start().starts_with("```") || line.trim_start().starts_with("~~~") {
            in_fence = !in_fence;
        }
        if !in_fence {
            if !skipped_h1 && line.starts_with("# ") {
                skipped_h1 = true;
                continue;
            }
            if skip.contains(&i) {
                continue;
            }
            if !is_doc && line.trim().eq_ignore_ascii_case("## comments") {
                comments_raw = Some(Vec::new());
                continue;
            }
            if let Some(c) = check.captures(line) {
                if !md.trim().is_empty() {
                    blocks.push(RawBlock::Md(std::mem::take(&mut md)));
                }
                md.clear();
                checks.push(CheckItem {
                    done: &c[2] != " ",
                    text: c[3].trim().to_string(),
                    line: i,
                    depth: c[1].len() / 2,
                });
                continue;
            }
        }
        if !checks.is_empty() {
            // A blank line inside a checklist keeps the run together.
            if line.trim().is_empty() {
                continue;
            }
            blocks.push(RawBlock::Checks(std::mem::take(&mut checks)));
        }
        md.push_str(line);
        md.push('\n');
    }
    if !checks.is_empty() {
        blocks.push(RawBlock::Checks(checks));
    }
    if !md.trim().is_empty() {
        blocks.push(RawBlock::Md(md));
    }
    if let Some(mut c) = comments_raw {
        comments_done.append(&mut c);
    }
    let comments = parse_comments(&comments_done);
    (blocks, comments)
}

/// `**Author** · when` or `### Author` starts an entry; text before the
/// first one is a single anonymous entry.
fn parse_comments(lines: &[&str]) -> Vec<(String, String, String)> {
    let head = regex::Regex::new(r"^\*\*(.+?)\*\*\s*[·•—-]\s*(.+)$").unwrap();
    let mut out: Vec<(String, String, String)> = Vec::new();
    let mut cur: Option<(String, String, String)> = None;
    for l in lines {
        let starts = head
            .captures(l)
            .map(|c| (c[1].to_string(), c[2].trim().to_string()))
            .or_else(|| l.strip_prefix("### ").map(|h| (h.trim().to_string(), String::new())));
        if let Some((a, w)) = starts {
            if let Some(c) = cur.take() {
                out.push(c);
            }
            cur = Some((a, w, String::new()));
            continue;
        }
        let c = cur.get_or_insert_with(|| ("Note".into(), String::new(), String::new()));
        c.2.push_str(l);
        c.2.push('\n');
    }
    if let Some(c) = cur {
        out.push(c);
    }
    out.into_iter()
        .filter(|(a, _, b)| !b.trim().is_empty() || a != "Note")
        .map(|(a, w, b)| (a, w, b.trim().to_string()))
        .collect()
}

pub fn md_style(cx: &App) -> TextViewStyle {
    let t = cx.theme();
    TextViewStyle::default()
        .paragraph_gap(rems(0.7))
        .inline_code(HighlightStyle {
            background_color: Some(t.muted_foreground.opacity(0.14)),
            ..Default::default()
        })
}

type Theme = gpui_kit::component::theme::Theme;

impl KuzgunApp {
    pub fn render_detail(&mut self, window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement + use<> {
        let Some(d) = self.detail.as_ref() else {
            return div().into_any_element();
        };
        let t = cx.theme().clone();
        let path = d.path.clone();
        let is_doc = d.is_doc;
        let full = d.full;
        let scroll = d.scroll.clone();
        let ix = self.board.find_path(&path);
        let wide = full || self.view.detail_w.unwrap_or(620.) >= 860.;

        let header = self.detail_header(ix, &path, is_doc, full, cx).into_any_element();
        let title: String = match ix {
            Some(i) => self.board.tickets[i].title.clone(),
            None => self
                .board
                .projects
                .iter()
                .flat_map(|p| p.docs.iter())
                .find(|doc| doc.path == path)
                .map(|doc| doc.title.clone())
                .unwrap_or_else(|| path.file_name().unwrap_or_default().to_string_lossy().to_string()),
        };
        let props = if is_doc { self.doc_panel(&path, cx) } else { self.props_panel(ix, cx) };
        let body = self.detail_body(&path, window, cx);
        let activity = (!is_doc).then(|| self.activity(ix, cx));
        let (props_inline, props_side) = if wide { (None, Some(props)) } else { (Some(props), None) };

        let main = div()
            .flex()
            .flex_col()
            .gap_4()
            .w_full()
            .min_w_0()
            .when(full, |d| d.max_w(px(820.)))
            .child(
                div()
                    .text_size(zrem(22.))
                    .line_height(zrem(30.))
                    .font_weight(FontWeight::SEMIBOLD)
                    .text_color(t.foreground)
                    .child(title),
            )
            .children(props_inline)
            .child(body)
            .children(activity);

        // Wide: the body scrolls, the properties column stays in place
        // (with its own scroll when it is taller than the window).
        let actions = if is_doc { None } else { self.detail_actions(ix, cx) };
        let (actions_side, actions_foot) = if wide { (actions, None) } else { (None, actions) };
        let body: AnyElement = if wide {
            div()
                .flex_1()
                .min_h_0()
                .flex()
                .flex_row()
                .child(
                    div()
                        .id("detail-scroll")
                        .flex_1()
                        .min_w_0()
                        .h_full()
                        .overflow_y_scroll()
                        .track_scroll(&scroll)
                        .child(div().p_6().flex().justify_center().child(main)),
                )
                .children(props_side.map(|p| {
                    div()
                        .w(px(360.))
                        .flex_none()
                        .h_full()
                        .flex()
                        .flex_col()
                        .border_l_1()
                        .border_color(t.border)
                        .child(
                            div()
                                .id("detail-side")
                                .flex_1()
                                .min_h_0()
                                .overflow_y_scroll()
                                .child(div().p_4().child(p)),
                        )
                        .children(actions_side)
                }))
                .into_any_element()
        } else {
            div()
                .id("detail-scroll")
                .flex_1()
                .min_h_0()
                .overflow_y_scroll()
                .track_scroll(&scroll)
                .child(div().p_5().child(main))
                .into_any_element()
        };
        div()
            .id("detail")
            .size_full()
            .flex_1()
            .min_w_0()
            .flex()
            .flex_col()
            .bg(t.background)
            .child(header)
            .child(body)
            .children(actions_foot)
            .into_any_element()
    }

    fn detail_header(&self, ix: Option<usize>, path: &Path, is_doc: bool, full: bool, cx: &mut Context<Self>) -> impl IntoElement + use<> {
        let t = cx.theme();
        let (muted, fg, border) = (t.muted_foreground, t.foreground, t.border);
        let project = ix
            .map(|i| self.board.tickets[i].project)
            .or_else(|| self.board.projects.iter().position(|p| p.docs.iter().any(|d| d.path == path)))
            .and_then(|p| self.board.projects.get(p));
        let key = ix
            .map(|i| self.board.tickets[i].key.clone())
            .unwrap_or_else(|| path.file_name().unwrap_or_default().to_string_lossy().to_string());
        let is_map = project.is_some_and(|p| p.map.is_some());
        let can_back = !self.nav_back.is_empty();
        let can_fwd = !self.nav_fwd.is_empty();
        let trail: Vec<String> = self.nav_back.iter().map(|(p, _)| self.page_label(p)).collect();
        let p = path.to_path_buf();
        let more = Button::new("detail-more")
            .ghost()
            .xsmall()
            .icon(Icon::new(IconName::Ellipsis).text_color(muted))
            .dropdown_menu(move |menu: PopupMenu, _, _| {
                let go = |f: fn(&mut KuzgunApp, PathBuf, &mut Context<KuzgunApp>)| {
                    let p = p.clone();
                    move |_: &ClickEvent, _: &mut Window, cx: &mut App| {
                        let p = p.clone();
                        with_app(cx, |a, cx| f(a, p, cx));
                    }
                };
                let menu = menu
                    .item(PopupMenuItem::new("Copy /implement Command").on_click(go(|a, p, cx| a.copy_command("implement", &p, cx))))
                    .item(PopupMenuItem::new("Copy /triage Command").on_click(go(|a, p, cx| a.copy_command("triage", &p, cx))));
                let menu = if is_map {
                    menu.item(PopupMenuItem::new("Copy /wayfinder Command").on_click(go(|a, p, cx| a.copy_command("wayfinder", &p, cx))))
                } else {
                    menu
                };
                menu.separator()
                    .item(PopupMenuItem::new("Open in Editor").on_click(go(|a, p, cx| a.open_in_editor(&p, cx))))
                    .item(PopupMenuItem::new("Reveal in Finder").on_click(go(|_, p, cx| cx.reveal_path(&p))))
                    .separator()
                    .item(PopupMenuItem::new("Copy ID").on_click(go(|a, _, cx| a.copy_current("ID", cx))))
                    .item(PopupMenuItem::new("Copy Title").on_click(go(|a, _, cx| a.copy_current("title", cx))))
                    .item(PopupMenuItem::new("Copy Path").on_click(go(|a, p, cx| a.copy("path", p.display().to_string(), cx))))
                    .item(PopupMenuItem::new("Copy as Markdown Link").on_click(go(|a, p, cx| {
                        let text = a
                            .board
                            .find_path(&p)
                            .map(|i| {
                                let t = &a.board.tickets[i];
                                format!("[{} {}]({})", t.key, t.title, crate::app::repo_relative(&t.path))
                            })
                            .unwrap_or_default();
                        a.copy("link", text, cx);
                    })))
            });
        div()
            .flex()
            .flex_none()
            .items_center()
            .gap_2()
            .h(px(40.))
            .px_3()
            .border_b_1()
            .border_color(border)
            .when(full && !is_doc, |d| {
                d.child(
                    Button::new("back-to-board")
                        .ghost()
                        .small()
                        .child(
                            div()
                                .flex()
                                .items_center()
                                .gap_1()
                                .text_sm()
                                .text_color(muted)
                                .child(Icon::new(IconName::ArrowLeft).size(px(14.)))
                                .child("Board"),
                        )
                        .tooltip("Back to the board (esc)")
                        .on_click(cx.listener(|this, _, w, cx| {
                            this.detail = None;
                            this.board_focus.focus(w, cx);
                            cx.notify();
                        })),
                )
                .child(div().w(px(1.)).h(px(16.)).bg(border))
            })
            .when(can_back || can_fwd, |d| {
                d.child(
                    Button::new("nav-back")
                        .ghost()
                        .xsmall()
                        .icon(Icon::new(IconName::ArrowLeft).text_color(if can_back { fg } else { muted.opacity(0.4) }))
                        .tooltip("Back ⌘[")
                        .on_click(cx.listener(|this, _, _, cx| this.nav_back_step(cx))),
                )
                .child(
                    Button::new("nav-fwd")
                        .ghost()
                        .xsmall()
                        .icon(Icon::new(IconName::ArrowRight).text_color(if can_fwd { fg } else { muted.opacity(0.4) }))
                        .tooltip("Forward ⌘]")
                        .on_click(cx.listener(|this, _, _, cx| this.nav_forward_step(cx))),
                )
            })
            .when_some(project, |d, p| {
                let name = p.name.clone();
                d.child(
                    div()
                        .id("crumb-project")
                        .flex()
                        .flex_none()
                        .items_center()
                        .gap_1p5()
                        .cursor_pointer()
                        .text_sm()
                        .text_color(muted)
                        .hover(|d| d.text_color(fg))
                        .child(div().size(px(8.)).rounded_full().bg(icons::tag_color(&p.name)))
                        .child(p.title.clone())
                        .tooltip(tip_text("Show this project's board".into()))
                        .on_click(cx.listener(move |this, _, w, cx| {
                            this.view.project = Some(name.clone());
                            this.detail = None;
                            this.save_view();
                            this.board_focus.focus(w, cx);
                            cx.notify();
                        })),
                )
                .child(Icon::new(IconName::ChevronRight).size(px(12.)).text_color(muted.opacity(0.6)))
            })
            // The pages this one was reached from, oldest first (last three).
            .when(!trail.is_empty(), |d| {
                let skip = trail.len().saturating_sub(3);
                d.when(skip > 0, |d| {
                    d.child(div().text_sm().text_color(muted).child("…"))
                        .child(Icon::new(IconName::ChevronRight).size(px(12.)).text_color(muted.opacity(0.6)))
                })
                .children(trail.into_iter().enumerate().skip(skip).map(|(i, label)| {
                    div()
                        .flex()
                        .flex_none()
                        .items_center()
                        .gap_2()
                        .child(
                            div()
                                .id(("crumb", i))
                                .text_sm()
                                .font_family(crate::settings::mono_font())
                                .text_color(muted)
                                .cursor_pointer()
                                .hover(|d| d.text_color(fg))
                                .child(label)
                                .on_click(cx.listener(move |this, _, _, cx| this.nav_jump(i, cx))),
                        )
                        .child(Icon::new(IconName::ChevronRight).size(px(12.)).text_color(muted.opacity(0.6)))
                }))
            })
            .child(
                div()
                    .min_w_0()
                    .truncate()
                    .text_sm()
                    .font_family(if is_doc { crate::settings::ui_font() } else { crate::settings::mono_font() })
                    .text_color(fg)
                    .child(key),
            )
            .child(div().flex_1())
            .when(!is_doc, |d| {
                d
                .child(
                    Button::new("detail-prev")
                        .ghost()
                        .xsmall()
                        .icon(Icon::new(IconName::ChevronUp).text_color(muted))
                        .tooltip("Previous (k)")
                        .on_click(cx.listener(|this, _, w, cx| this.move_selection(0, -1, w, cx))),
                )
                .child(
                    Button::new("detail-next")
                        .ghost()
                        .xsmall()
                        .icon(Icon::new(IconName::ChevronDown).text_color(muted))
                        .tooltip("Next (j)")
                        .on_click(cx.listener(|this, _, w, cx| this.move_selection(0, 1, w, cx))),
                )
            })
            .child(more)
            .child(
                Button::new("detail-expand")
                    .ghost()
                    .xsmall()
                    .icon(Icon::new(if full { IconName::Minimize2 } else { IconName::Maximize2 }).text_color(muted))
                    .tooltip(if full { "Back to board (esc)" } else { "Open full view (enter)" })
                    .on_click(cx.listener(|this, _, _, cx| {
                        if let Some(d) = &mut this.detail {
                            d.full = !d.full;
                        }
                        cx.notify();
                    })),
            )
            .child(
                Button::new("detail-close")
                    .ghost()
                    .xsmall()
                    .icon(Icon::new(IconName::X).text_color(muted))
                    .tooltip("Close (esc)")
                    .on_click(cx.listener(|this, _, w, cx| {
                        this.detail = None;
                        this.board_focus.focus(w, cx);
                        cx.notify();
                    })),
            )
    }

    // ---------- properties ----------

    fn props_panel(&self, ix: Option<usize>, cx: &mut Context<Self>) -> AnyElement {
        let Some(ix) = ix else {
            return div().into_any_element();
        };
        let tk = &self.board.tickets[ix];
        let theme = cx.theme().clone();
        let (muted, fg, border) = (theme.muted_foreground, theme.foreground, theme.border);
        let light = crate::settings::is_light(cx);
        let project = &self.board.projects[tk.project];

        // ---- readiness banner ----
        let blocked = self.idx.blocked.get(ix).copied().unwrap_or(false);
        let frontier = self.idx.frontier.get(ix).copied().unwrap_or(false);
        let open_blockers = self.idx.open_blockers.get(ix).cloned().unwrap_or_default();
        let (tone, icon, title, detail): (Hsla, IconName, String, String) = if tk.category.is_closed() {
            (icons::status_color(tk.category, light), IconName::CircleCheck, "Closed".into(), format!("{} · nothing left to do", status_label(&tk.status)))
        } else if blocked {
            let n = open_blockers.len();
            let projects: Vec<String> = self.blocking_projects(ix).iter().map(|&p| self.board.projects[p].title.clone()).collect();
            let mut parts = Vec::new();
            if n > 0 {
                parts.push(format!("{n} open ticket{}", if n == 1 { "" } else { "s" }));
            }
            if !projects.is_empty() {
                parts.push(format!("the {} project to close", projects.join(" and ")));
            }
            (theme.red, IconName::Lock, "Blocked".into(), format!("Waiting on {}", parts.join(" and ")))
        } else if frontier {
            (theme.green, IconName::Compass, "Ready to start".into(), "On the frontier: every blocker is closed".into())
        } else {
            match tk.category {
                Category::Backlog => (muted, IconName::CircleDashed, "Not ready yet".into(), "Draft or waiting on triage".into()),
                Category::InReview => (icons::status_color(tk.category, light), IconName::Eye, "In review".into(), "Built; waiting on a review".into()),
                _ => (icons::status_color(tk.category, light), IconName::Clock, "In progress".into(), "Claimed: an agent or a person is on it".into()),
            }
        };
        // A live agent run says more than the file does.
        let (tone, icon, title, detail) = match &tk.agent {
            Some(run) => {
                let (tone, title) = match run.state {
                    crate::agents::RunState::Running => (theme.green, "An agent is working on this"),
                    crate::agents::RunState::AwaitingReview => (theme.yellow, "Agent finished: waiting on review"),
                    crate::agents::RunState::Finished => (muted, "Agent finished"),
                };
                (tone, IconName::Bot, title.to_string(), run.description.clone())
            }
            None => (tone, icon, title, detail),
        };
        let mut banner = div()
            .flex()
            .flex_col()
            .gap_1()
            .p_3()
            .rounded(px(10.))
            .bg(tone.opacity(0.1))
            .border_1()
            .border_color(tone.opacity(0.3))
            .child(
                div()
                    .flex()
                    .items_center()
                    .gap_2()
                    .child(Icon::new(icon).size(px(16.)).text_color(tone))
                    .child(div().text_sm().font_weight(FontWeight::SEMIBOLD).text_color(fg).child(title)),
            )
            .child(div().pl(px(24.)).text_sm().text_color(muted).child(detail));
        if let Some(run) = &tk.agent {
            let mut facts = vec![
                format!("Started {}", ago_label(now_unix() - run.started)),
                format!("last activity {}", ago_label(now_unix() - run.last_activity)),
            ];
            if let Some(w) = &run.worktree {
                facts.push(format!("worktree {}", w.file_name().unwrap_or_default().to_string_lossy()));
            }
            banner = banner
                .child(div().pl(px(24.)).text_xs().text_color(muted).child(facts.join(" · ")))
                .child(
                    div()
                        .pl(px(24.))
                        .text_xs()
                        .text_color(muted)
                        .child(format!("The file still says \"{}\": /implement does not update it.", status_label(&tk.status))),
                );
            let wt = run.worktree.clone();
            let ticket_path = tk.path.clone();
            banner = banner.child(
                div()
                    .pl(px(24.))
                    .pt_1()
                    .flex()
                    .gap_2()
                    .when_some(wt, |d, wt| {
                        d.child(
                            Button::new("agent-worktree")
                                .xsmall()
                                .icon(Icon::new(IconName::FolderGit2))
                                .label("Reveal worktree")
                                .on_click(move |_, _, cx| cx.reveal_path(&wt)),
                        )
                    })
                    .child(
                        Button::new("agent-transcript")
                            .xsmall()
                            .ghost()
                            .icon(Icon::new(IconName::FileText))
                            .label("Agent session")
                            .on_click(cx.listener(move |this, _, _, cx| this.open_session(ticket_path.clone(), cx))),
                    ),
            );
        } else if blocked {
            banner = banner.child(div().mt_1().flex().flex_col().children(open_blockers.iter().map(|&j| self.relation_row("rel-banner", j, cx))));
        }

        // ---- properties ----
        let row = |icon: AnyElement, label: &str, value: AnyElement| -> AnyElement {
            div()
                .flex()
                .items_center()
                .min_h(px(32.))
                .gap_2()
                .child(div().w(px(18.)).flex_none().flex().justify_center().child(icon))
                .child(div().w(px(84.)).flex_none().text_sm().text_color(muted).child(label.to_string()))
                .child(div().flex_1().min_w_0().flex().items_center().text_sm().text_color(fg).child(value))
                .into_any_element()
        };
        let ic = |name: IconName| Icon::new(name).size(px(15.)).text_color(muted).into_any_element();
        let text = |s: String| div().min_w_0().truncate().child(s).into_any_element();
        let meaning = self
            .board
            .roles
            .get(&tk.status_key)
            .map(|(r, m)| format!("{r}: {m}"))
            .or_else(|| model::role_meaning(&tk.status_key).map(str::to_string));
        let status_value = div()
            .id("prop-status")
            .flex()
            .items_center()
            .gap_1p5()
            .min_w_0()
            .child(div().min_w_0().truncate().child(status_label(&tk.status_key)))
            .when(tk.status_derived, |d| d.child(div().text_xs().text_color(muted).child("derived")))
            .when_some(tk.inferred.clone(), |d, why| {
                d.child(div().text_xs().text_color(muted).child(format!("file: {}", tk.status)))
                    .tooltip(tip_text(format!("{why}. The file still says \"{}\".", tk.status)))
            })
            .when_some(meaning, |d, m| d.tooltip(tip_text(m)))
            .into_any_element();
        let mut props = div().flex().flex_col().child(row(
            icons::status_icon(tk.category).size(px(15.)).text_color(icons::status_color(tk.category, light)).into_any_element(),
            "Status",
            status_value,
        ));
        if let Some(m) = self.idx.modes.get(ix).copied().flatten() {
            let (i, c, what) = match m {
                Mode::Afk => (IconName::Bot, theme.blue, "AFK · agent alone"),
                Mode::Hitl => (IconName::User, theme.accent, "HITL · needs a person"),
            };
            props = props.child(row(
                Icon::new(i).size(px(15.)).text_color(c).into_any_element(),
                "Mode",
                div()
                    .px_2()
                    .py_0p5()
                    .rounded(px(6.))
                    .bg(c.opacity(0.14))
                    .text_color(c)
                    .text_sm()
                    .child(what)
                    .into_any_element(),
            ));
        }
        if let Some(k) = &tk.kind {
            props = props.child(row(ic(IconName::Tag), "Type", text(model::humanize(k))));
        }
        let pname = project.name.clone();
        props = props.child(row(
            div().size(px(9.)).rounded_full().bg(icons::tag_color(&project.name)).into_any_element(),
            "Project",
            div()
                .id("prop-project")
                .min_w_0()
                .truncate()
                .cursor_pointer()
                .hover(|d| d.text_color(theme.link))
                .child(project.title.clone())
                .on_click(cx.listener(move |this, _, _, cx| {
                    this.view.project = Some(pname.clone());
                    this.save_view();
                    cx.notify();
                }))
                .into_any_element(),
        ));
        if let Some(spec) = tk.spec_link.clone() {
            let raw = tk.prop("spec").or(tk.prop("prd")).or(tk.prop("map")).unwrap_or_default();
            let name = link_text(raw).unwrap_or_else(|| "Spec".into());
            props = props.child(row(ic(IconName::BookOpen), "Spec", self.doc_link("prop-spec", name, spec, cx)));
        }
        // People, from git: who wrote it, who did it, who touched it.
        let ring = theme.background;
        let fg_git = self.ages.get(&tk.path).cloned();
        if let Some(g) = &fg_git
            && !g.reporter.is_empty()
        {
            props = props.child(row(
                ic(IconName::UserPen),
                "Reporter",
                div()
                    .flex()
                    .items_center()
                    .gap_2()
                    .child(crate::board::avatar(&g.reporter, 20., ring))
                    .child(div().min_w_0().truncate().child(g.reporter.clone()))
                    .into_any_element(),
            ));
        }
        let mut doers = self.assignees(ix).unwrap_or_default();
        if let Some(v) = &tk.assignee
            && !doers.contains(v)
        {
            doers.insert(0, v.clone());
        }
        props = props.child(row(
            ic(IconName::User),
            "Assignee",
            if doers.is_empty() {
                div().text_color(muted).child("Nobody yet").into_any_element()
            } else {
                div()
                    .flex()
                    .items_center()
                    .gap_2()
                    .min_w_0()
                    .child(crate::board::avatar_group(&doers, 20., ring, 4, muted))
                    .child(div().min_w_0().truncate().child(doers.join(", ")))
                    .into_any_element()
            },
        ));
        if let Some(g) = &fg_git
            && g.contributors.len() > 1
        {
            let names: Vec<String> = g.contributors.iter().map(|(n, _)| n.clone()).collect();
            let detail = g
                .contributors
                .iter()
                .map(|(n, c)| format!("{n} · {c} commit{}", if *c == 1 { "" } else { "s" }))
                .collect::<Vec<_>>()
                .join("\n");
            props = props.child(row(
                ic(IconName::Users),
                "Contributors",
                div()
                    .id("contributors")
                    .flex()
                    .items_center()
                    .gap_2()
                    .child(crate::board::avatar_group(&names, 20., ring, 5, muted))
                    .child(div().text_color(muted).child(format!("{}", names.len())))
                    .tooltip(tip_text(detail))
                    .into_any_element(),
            ));
        }
        let known = [
            "status", "type", "spec", "prd", "map", "blocked by", "blocked_by", "depends on", "what to build",
            "needs a human", "title", "claimed by", "claimed_by", "assignee",
        ];
        for (k, v) in &tk.props {
            if known.contains(&k.to_lowercase().as_str()) || v.chars().count() > 60 {
                continue;
            }
            let icon = if model::is_milestone(k) { IconName::Diamond } else { IconName::Hash };
            props = props.child(row(ic(icon), &model::field_label(k), text(v.clone())));
        }
        let (done, total) = tk.checklist_counts();
        if total > 0 {
            props = props.child(row(ic(IconName::ListChecks), "Sub-tasks", progress(done, total, &theme, light).into_any_element()));
        }

        let attention = self.idx.attention.get(ix).cloned().unwrap_or_default();
        let attention_box = (!attention.is_empty()).then(|| {
            div()
                .flex()
                .flex_col()
                .gap_1()
                .p_3()
                .rounded(px(10.))
                .bg(theme.yellow.opacity(0.08))
                .border_1()
                .border_color(theme.yellow.opacity(0.3))
                .child(
                    div()
                        .flex()
                        .items_center()
                        .gap_2()
                        .child(Icon::new(IconName::TriangleAlert).size(px(16.)).text_color(theme.yellow))
                        .child(div().text_sm().font_weight(FontWeight::SEMIBOLD).text_color(fg).child("Needs attention")),
                )
                .children(attention.into_iter().map(|a| div().pl(px(24.)).text_sm().text_color(muted).child(a)))
        });
        let mut col = div().flex().flex_col().gap_3().child(banner).children(attention_box).child(section_box("Properties", props.into_any_element(), !self.is_folded("detail:Properties"), &theme));

        if let Some(h) = &tk.needs_human {
            col = col.child(
                div()
                    .p_3()
                    .rounded(px(10.))
                    .bg(theme.accent.opacity(0.1))
                    .border_1()
                    .border_color(theme.accent.opacity(0.3))
                    .flex()
                    .flex_col()
                    .gap_1()
                    .child(
                        div()
                            .flex()
                            .items_center()
                            .gap_2()
                            .child(Icon::new(IconName::Hand).size(px(16.)).text_color(theme.accent))
                            .child(div().text_sm().font_weight(FontWeight::SEMIBOLD).text_color(fg).child("Needs a human")),
                    )
                    .child(div().pl(px(24.)).text_sm().text_color(muted).child(h.clone())),
            );
        }

        // ---- relations: one list, a header row per kind ----
        let mut groups: Vec<(&str, Vec<AnyElement>)> = Vec::new();
        let mut blocked_rows: Vec<AnyElement> = Vec::new();
        let mut shown = Vec::new();
        for r in &tk.blocked_refs {
            let hit = r.hit;
            match hit {
                Some(j) if !shown.contains(&j) => {
                    shown.push(j);
                    blocked_rows.push(self.relation_row("rel-by", j, cx));
                }
                Some(_) => {}
                None => {
                    let label = link_text(&r.text).unwrap_or_else(|| r.text.clone());
                    blocked_rows.push(match r.path.as_ref().filter(|p| p.is_file()).cloned() {
                        Some(p) => self.doc_row(("ref-doc", blocked_rows.len()), model::humanize(&label), p, cx),
                        None => div()
                            .flex()
                            .items_center()
                            .gap_2()
                            .h(px(36.))
                            .px_3()
                            .text_sm()
                            .text_color(muted)
                            .child(Icon::new(IconName::CircleQuestionMark).flex_none().size(px(14.)))
                            .child(div().flex_1().min_w_0().truncate().child(label))
                            .child(div().flex_none().text_xs().child("not on this board"))
                            .into_any_element(),
                    });
                }
            }
        }
        if !blocked_rows.is_empty() {
            groups.push(("Blocked by", blocked_rows));
        }
        if !tk.blocks.is_empty() {
            groups.push(("Blocks", tk.blocks.iter().map(|&j| self.relation_row("rel-blocks", j, cx)).collect()));
        }
        if !tk.related.is_empty() {
            groups.push(("Related", tk.related.iter().map(|&j| self.relation_row("rel-related", j, cx)).collect()));
        }
        let relations: AnyElement = if groups.is_empty() {
            div().text_sm().text_color(muted).child("No blockers and nothing waits on it.").into_any_element()
        } else {
            let mut list = div().flex().flex_col().rounded(px(8.)).border_1().border_color(border).overflow_hidden();
            for (gi, (title, rows)) in groups.into_iter().enumerate() {
                let n = rows.len();
                list = list.child(
                    div()
                        .flex()
                        .items_center()
                        .gap_1p5()
                        .h(px(28.))
                        .px_3()
                        .bg(muted.opacity(0.06))
                        .when(gi > 0, |d| d.border_t_1().border_color(border))
                        .text_xs()
                        .font_weight(FontWeight::MEDIUM)
                        .text_color(muted)
                        .child(title.to_string())
                        .child(div().text_color(muted.opacity(0.7)).child(n.to_string())),
                );
                for r in rows {
                    list = list.child(div().border_t_1().border_color(border).child(r));
                }
            }
            list.into_any_element()
        };
        col = col.child(section_box("Relations", relations, !self.is_folded("detail:Relations"), &theme));

        // ---- details: label / value rows ----
        let hist = self.detail.as_ref().and_then(|d| d.history.clone());
        let mut facts: Vec<(IconName, &str, String)> = Vec::new();
        facts.push((IconName::Clock, "Modified", crate::app::ago_since(tk.modified)));
        match &hist {
            Some(h) if h.in_repo => {
                if let Some(c) = h.commits.last() {
                    facts.push((IconName::CalendarPlus, "Created", ago_label(now_unix() - c.time)));
                    facts.push((IconName::User, "Author", c.author.clone()));
                }
                if let Some(since) = h.status_since {
                    let days = (now_unix() - since) / 86_400;
                    facts.push((IconName::Hourglass, "In status", format!("{days} day{}", if days == 1 { "" } else { "s" })));
                }
                facts.push((IconName::GitBranch, "Branch", h.branch.clone().unwrap_or_default()));
                facts.push((IconName::GitCommitHorizontal, "Commits", h.commits.len().to_string()));
                let state = match h.worktree.as_deref().map(str::trim) {
                    None => "Clean",
                    Some("??") => "Untracked",
                    Some("A") => "Added, not committed",
                    Some(_) => "Uncommitted changes",
                };
                facts.push((IconName::CircleDot, "Git", state.into()));
            }
            Some(_) => facts.push((IconName::GitBranch, "Git", "Not in a repository".into())),
            None => facts.push((IconName::GitBranch, "Git", "Reading…".into())),
        }
        facts.push((IconName::Type, "Size", format!("{} words · {:.1} KB", tk.words, tk.bytes as f32 / 1024.)));
        let rel_path = crate::app::repo_relative(&tk.path);
        let reveal = tk.path.clone();
        let mut details = div().flex().flex_col().child(row(
            ic(IconName::FileText),
            "Path",
            div()
                .id("detail-path")
                .min_w_0()
                .truncate()
                .text_xs()
                .font_family(crate::settings::mono_font())
                .cursor_pointer()
                .hover(|d| d.text_color(theme.link))
                .child(tk.path.file_name().unwrap_or_default().to_string_lossy().to_string())
                .tooltip(tip_text(format!("{rel_path}\nClick to reveal in Finder")))
                .on_click(move |_, _, cx| cx.reveal_path(&reveal))
                .into_any_element(),
        ));
        for (icon, label, value) in facts {
            let v: AnyElement = if label == "Git" {
                let c = if value == "Clean" { theme.green } else { theme.yellow };
                div()
                    .flex()
                    .items_center()
                    .gap_1p5()
                    .child(div().size(px(7.)).rounded_full().bg(c))
                    .child(value)
                    .into_any_element()
            } else {
                text(value)
            };
            details = details.child(row(ic(icon), label, v));
        }
        col = col.child(section_box("Details", details.into_any_element(), !self.is_folded("detail:Details"), &theme));

        let _ = border;
        col.into_any_element()
    }

    fn doc_link(&self, id: impl Into<ElementId>, name: String, path: PathBuf, cx: &mut Context<Self>) -> AnyElement {
        let link = cx.theme().link;
        let path = std::fs::canonicalize(&path).unwrap_or(path);
        let icon = if path.file_name().is_some_and(|n| n.eq_ignore_ascii_case("map.md")) { IconName::Map } else { IconName::BookOpen };
        div()
            .id(id)
            .flex()
            .items_center()
            .gap_1p5()
            .min_w_0()
            .py_1()
            .cursor_pointer()
            .text_sm()
            .text_color(link)
            .child(Icon::new(icon).flex_none().size(px(13.)))
            .child(div().min_w_0().truncate().child(name))
            .on_click(cx.listener(move |this, _, _, cx| this.navigate(path.clone(), true, cx)))
            .into_any_element()
    }

    /// The ticket's actions, pinned under the properties.
    fn detail_actions(&self, ix: Option<usize>, cx: &mut Context<Self>) -> Option<AnyElement> {
        let tk = &self.board.tickets[ix?];
        let border = cx.theme().border;
        let path = tk.path.clone();
        let p2 = path.clone();
        let p3 = path.clone();
        let p4 = path.clone();
        let p5 = path.clone();
        let next = self.next_command(ix?);
        let runs = self.runs_of(ix?);
        let has_runs = !runs.is_empty();
        let running = runs.iter().any(|r| r.state == crate::agents::RunState::Running);
        let prefs = crate::settings::get();
        let editor_label = if !prefs.editor_command.trim().is_empty() {
            "Open in Editor".to_string()
        } else if prefs.editor_app.is_empty() {
            "Open in Editor".to_string()
        } else {
            format!("Open in {}", prefs.editor_app)
        };
        Some(
            div()
                .flex_none()
                .flex()
                .flex_col()
                .gap_2()
                .p_3()
                .border_t_1()
                .border_color(border)
                // A ticket an agent worked on opens its session first.
                .when(has_runs, |d| {
                    let p6 = p5.clone();
                    let start = next.clone().map(|(skill, _, why)| (skill, why));
                    let p7 = p5.clone();
                    let term = crate::terminals::chosen().map(|t| t.name).unwrap_or_else(|| "a terminal".into());
                    d.child(
                        div()
                            .flex()
                            .gap_2()
                            .child(
                                Button::new("act-session")
                                    .primary()
                                    .flex_1()
                                    .icon(Icon::new(IconName::Bot))
                                    .label(if running { "Watch agent" } else { "Agent session" })
                                    .tooltip("Read what the agent did, step by step")
                                    .on_click(cx.listener(move |this, _, _, cx| this.open_session(p6.clone(), cx))),
                            )
                            .when_some(start, |d, (skill, why)| {
                                d.child(
                                    Button::new("act-start")
                                        .flex_1()
                                        .icon(Icon::new(IconName::Play))
                                        .label("Start agent")
                                        .tooltip(format!("{why}: runs `claude` with /{skill} in {term}"))
                                        .on_click(cx.listener(move |this, _, _, cx| this.start_agent(&p7, cx))),
                                )
                            }),
                    )
                })
                .when_some(next.filter(|_| !has_runs), |d, (skill, cmd, why)| {
                    let p5 = p5.clone();
                    let term = crate::terminals::chosen().map(|t| t.name).unwrap_or_else(|| "a terminal".into());
                    d.child(
                        div()
                            .flex()
                            .gap_2()
                            .child(
                                Button::new("act-start")
                                    .primary()
                                    .flex_1()
                                    .icon(Icon::new(IconName::Play))
                                    .label("Start agent")
                                    .tooltip(format!("{why}: runs `claude` with /{skill} in {term}"))
                                    .on_click(cx.listener(move |this, _, _, cx| this.start_agent(&p5, cx))),
                            )
                            .child(
                                Button::new("act-next")
                                    .flex_1()
                                    .icon(Icon::new(IconName::Copy))
                                    .label(format!("Copy /{skill}"))
                                    .tooltip(format!("{why}\n{cmd}"))
                                    .on_click(cx.listener(move |this, _, _, cx| this.copy("command", cmd.clone(), cx))),
                            ),
                    )
                })
                .child(
                    div()
                        .flex()
                        .gap_2()
                        .child(
                            div().flex_1().child(
                                DropdownButton::new("act-editor")
                                    .w_full()
                                    .button(
                                        Button::new("act-editor-open")
                                            .flex_1()
                                            .icon(Icon::new(IconName::SquarePen))
                                            .label(editor_label)
                                            .tooltip("Open in Editor ⌘E")
                                            .on_click(cx.listener(move |this, _, _, cx| this.open_in_editor(&p2, cx))),
                                    )
                                    .dropdown_menu(move |mut menu: PopupMenu, _, _| {
                                        let current = crate::settings::get().editor_app.clone();
                                        let mk = |label: String, name: String, on: bool| {
                                            let p = p4.clone();
                                            PopupMenuItem::new(label).checked(on).on_click(move |_, _, cx| {
                                                let (name, p) = (name.clone(), p.clone());
                                                with_app(cx, |a, cx| a.open_with(name, &p, cx));
                                            })
                                        };
                                        menu = menu.item(mk("System default".into(), String::new(), current.is_empty()));
                                        menu = menu.separator();
                                        for e in crate::editors::installed() {
                                            menu = menu.item(mk(e.name.clone(), e.name.clone(), current == e.name));
                                        }
                                        menu
                                    }),
                            ),
                        )
                        .child(
                            Button::new("act-reveal")
                                .flex_1()
                                .icon(Icon::new(IconName::FolderOpen))
                                .label("Reveal")
                                .on_click(move |_, _, cx| cx.reveal_path(&p3)),
                        ),
                )
                .into_any_element(),
        )
    }

    fn relation_row(&self, scope: &'static str, j: usize, cx: &mut Context<Self>) -> AnyElement {
        let o = &self.board.tickets[j];
        let t = cx.theme();
        let (muted, fg) = (t.muted_foreground, t.foreground);
        let light = crate::settings::is_light(cx);
        let color = icons::status_color(o.category, light);
        let p = o.path.clone();
        div()
            .id((scope, j))
            .flex()
            .items_center()
            .gap_2()
            .h(px(36.))
            .px_3()
            .cursor_pointer()
            .hover(|d| d.bg(muted.opacity(0.08)))
            .child(icons::status_icon(o.category).flex_none().size(px(14.)).text_color(color))
            .child(
                div()
                    .flex_none()
                    .text_xs()
                    .font_family(crate::settings::mono_font())
                    .text_color(muted)
                    .child(o.key.clone()),
            )
            .child(div().flex_1().min_w_0().truncate().text_sm().text_color(fg).child(o.title.clone()))
            .child(
                div()
                    .flex_none()
                    .px_1p5()
                    .py_0p5()
                    .rounded(px(5.))
                    .bg(color.opacity(0.14))
                    .text_xs()
                    .text_color(color)
                    .child(status_label(&o.status)),
            )
            .tooltip(tip_text(format!("{} {} · {}", o.key, o.title, status_label(&o.status))))
            .on_click(cx.listener(move |this, _, _, cx| this.navigate(p.clone(), false, cx)))
            .into_any_element()
    }

    /// A linked doc (spec, map) as a relation row.
    fn doc_row(&self, id: impl Into<ElementId>, name: String, path: PathBuf, cx: &mut Context<Self>) -> AnyElement {
        let t = cx.theme();
        let (muted, fg, link) = (t.muted_foreground, t.foreground, t.link);
        let path = std::fs::canonicalize(&path).unwrap_or(path);
        let file = path.file_name().unwrap_or_default().to_string_lossy().to_string();
        let icon = if file.eq_ignore_ascii_case("map.md") { IconName::Map } else { IconName::BookOpen };
        div()
            .id(id)
            .flex()
            .items_center()
            .gap_2()
            .h(px(36.))
            .px_3()
            .cursor_pointer()
            .hover(|d| d.bg(muted.opacity(0.08)))
            .child(Icon::new(icon).flex_none().size(px(14.)).text_color(link))
            .child(div().flex_1().min_w_0().truncate().text_sm().text_color(fg).child(name))
            .child(
                div()
                    .flex_none()
                    .px_1p5()
                    .py_0p5()
                    .rounded(px(5.))
                    .bg(link.opacity(0.14))
                    .text_xs()
                    .text_color(link)
                    .child(file),
            )
            .on_click(cx.listener(move |this, _, _, cx| this.navigate(path.clone(), true, cx)))
            .into_any_element()
    }

    /// A project doc (spec / map): project progress and its tickets.
    fn doc_panel(&self, path: &Path, cx: &mut Context<Self>) -> AnyElement {
        let Some(pi) = self.board.projects.iter().position(|p| p.docs.iter().any(|d| d.path == path)) else {
            return div().into_any_element();
        };
        let theme = cx.theme().clone();
        let light = crate::settings::is_light(cx);
        let tickets: Vec<usize> = (0..self.board.tickets.len()).filter(|&i| self.board.tickets[i].project == pi).collect();
        let done = tickets.iter().filter(|&&i| self.board.tickets[i].category.is_closed()).count();
        let frontier: Vec<usize> = tickets.iter().copied().filter(|&i| self.idx.frontier.get(i).copied().unwrap_or(false)).collect();
        let mut col = div()
            .flex()
            .flex_col()
            .gap_1()
            .child(div().text_xs().text_color(theme.muted_foreground).child("Project progress"))
            .child(progress(done, tickets.len(), &theme, light));
        // Milestones of this project (Tranche, Phase, Sprint...), in order.
        for f in self.board.facets.iter().filter(|f| model::is_milestone(&f.key)) {
            let rows: Vec<(String, usize, usize)> = f
                .values
                .iter()
                .map(|v| {
                    let ids: Vec<usize> =
                        tickets.iter().copied().filter(|&i| self.board.tickets[i].field_values(&f.key).iter().any(|x| x == v)).collect();
                    let closed = ids.iter().filter(|&&i| self.board.tickets[i].category.is_closed()).count();
                    (v.clone(), closed, ids.len())
                })
                .filter(|(_, _, n)| *n > 0)
                .collect();
            if rows.is_empty() {
                continue;
            }
            col = col.child(div().mt_3().text_xs().text_color(theme.muted_foreground).child(model::field_label(&f.key)));
            for (v, closed, n) in rows {
                let frac = closed as f32 / n as f32;
                let color = if closed == n { icons::status_color(Category::Done, light) } else { theme.accent };
                col = col.child(
                    div()
                        .flex()
                        .items_center()
                        .gap_2()
                        .h(px(26.))
                        .child(icons::diamond(frac).size(px(13.)).text_color(color))
                        .child(div().w(px(56.)).flex_none().truncate().text_sm().text_color(theme.foreground).child(v))
                        .child(progress(closed, n, &theme, light)),
                );
            }
        }
        if !frontier.is_empty() {
            col = col.child(
                div()
                    .mt_3()
                    .flex()
                    .items_center()
                    .gap_1p5()
                    .text_xs()
                    .text_color(theme.green)
                    .child(Icon::new(IconName::Compass).size(px(12.)))
                    .child(format!("Frontier · {}", frontier.len())),
            );
            for j in frontier {
                col = col.child(self.relation_row("rel-doc", j, cx));
            }
        }
        for c in Category::ALL {
            let ids: Vec<usize> = tickets.iter().copied().filter(|&i| self.board.tickets[i].category == c).collect();
            if ids.is_empty() {
                continue;
            }
            col = col.child(
                div()
                    .mt_3()
                    .flex()
                    .items_center()
                    .gap_1p5()
                    .text_xs()
                    .text_color(theme.muted_foreground)
                    .child(icons::status_icon(c).size(px(12.)).text_color(icons::status_color(c, light)))
                    .child(format!("{} · {}", c.label(), ids.len())),
            );
            for j in ids.into_iter().take(60) {
                col = col.child(self.relation_row("rel-doc", j, cx));
            }
        }
        col.into_any_element()
    }

    // ---------- body ----------

    fn detail_body(&mut self, path: &Path, _window: &mut Window, cx: &mut Context<Self>) -> AnyElement {
        let theme = cx.theme().clone();
        let light = crate::settings::is_light(cx);
        let Some(d) = self.detail.as_ref() else {
            return div().into_any_element();
        };
        let style = md_style(cx);
        let base = path.to_path_buf();
        let (mut total, mut done) = (0, 0);
        for b in &d.blocks {
            if let Block::Checks(c) = b {
                total += c.len();
                done += c.iter().filter(|x| x.done).count();
            }
        }
        let first_checks = d.blocks.iter().position(|b| matches!(b, Block::Checks(_)));
        let mut col = div().flex().flex_col().gap_3().min_w_0().text_sm().text_color(theme.foreground);
        for (bi, b) in d.blocks.iter().enumerate() {
            match b {
                Block::Md(state) => {
                    let base = base.clone();
                    col = col.child(
                        TextView::new(state)
                            .selectable(true)
                            .style(style.clone())
                            .on_link_click(move |url, _, window, cx| {
                                let url = url.to_string();
                                let base = base.clone();
                                let view = cx.global::<KuzgunHandle>().0.clone();
                                view.update(cx, |this, cx| this.follow_link(&base, &url, window, cx));
                            }),
                    );
                }
                Block::Checks(items) => {
                    let mut list = div()
                        .flex()
                        .flex_col()
                        .my_3()
                        .rounded(px(10.))
                        .border_1()
                        .border_color(theme.border)
                        .pb_1();
                    if Some(bi) == first_checks {
                        list = list.child(
                            div()
                                .flex()
                                .items_center()
                                .gap_2()
                                .px_3()
                                .h(px(38.))
                                .mb_1()
                                .border_b_1()
                                .border_color(theme.border)
                                .text_sm()
                                .text_color(theme.muted_foreground)
                                .child(Icon::new(IconName::ListChecks).size(px(14.)))
                                .child("Sub-tasks")
                                .child(div().flex_1())
                                .child(progress(done, total, &theme, light)),
                        );
                    }
                    for item in items {
                        list = list.child(check_row(item, &theme, &style));
                    }
                    col = col.child(list);
                }
            }
        }
        col.into_any_element()
    }

    // ---------- activity ----------

    fn activity(&self, ix: Option<usize>, cx: &mut Context<Self>) -> AnyElement {
        let Some(d) = self.detail.as_ref() else {
            return div().into_any_element();
        };
        let theme = cx.theme().clone();
        let (muted, fg, border) = (theme.muted_foreground, theme.foreground, theme.border);
        let light = crate::settings::is_light(cx);
        let tab = d.tab;
        let tabs = div().flex().gap_1().children([ActivityTab::All, ActivityTab::Comments, ActivityTab::History].into_iter().map(|t| {
            let on = t == tab;
            let label = match t {
                ActivityTab::All => "All".to_string(),
                ActivityTab::Comments => format!("Comments · {}", d.comments.len()),
                ActivityTab::History => format!("History · {}", d.history.as_ref().map(|h| h.commits.len()).unwrap_or(0)),
            };
            div()
                .id(match t {
                    ActivityTab::All => "tab-all",
                    ActivityTab::Comments => "tab-comments",
                    ActivityTab::History => "tab-history",
                })
                .px_2p5()
                .h(px(28.))
                .flex()
                .items_center()
                .rounded(px(6.))
                .cursor_pointer()
                .text_sm()
                .when(on, |d| d.bg(muted.opacity(0.15)).text_color(fg))
                .when(!on, |d| d.text_color(muted))
                .hover(|d| d.bg(muted.opacity(0.1)))
                .child(label)
                .on_click(cx.listener(move |this, _, _, cx| {
                    if let Some(d) = &mut this.detail {
                        d.tab = t;
                    }
                    cx.notify();
                }))
        }));

        let mut events: Vec<(i64, AnyElement)> = Vec::new();
        if tab != ActivityTab::Comments {
            match &d.history {
                Some(h) if h.in_repo => {
                    if h.worktree.is_some() {
                        let secs = ix
                            .and_then(|i| self.board.tickets[i].modified)
                            .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
                            .map(|d| d.as_secs() as i64)
                            .unwrap_or(now_unix());
                        events.push((
                            secs,
                            event_row(
                                Icon::new(IconName::FilePen).text_color(theme.yellow),
                                "Changed on disk, not committed yet".into(),
                                ago_label(now_unix() - secs),
                                None,
                                &theme,
                            ),
                        ));
                    }
                    for c in &h.commits {
                        let mut what: Vec<String> = Vec::new();
                        if c.created {
                            what.push("created the ticket".into());
                        }
                        let mut icon = Icon::new(IconName::GitCommitHorizontal).text_color(muted);
                        if let Some((from, to)) = &c.status_change {
                            let cat = model::categorize(to);
                            icon = icons::status_icon(cat).text_color(icons::status_color(cat, light));
                            if from.is_empty() {
                                what.push(format!("set status to {}", status_label(to)));
                            } else {
                                what.push(format!("moved {} → {}", status_label(from), status_label(to)));
                            }
                        }
                        if c.checked > 0 {
                            what.push(format!("checked {} sub-task{}", c.checked, if c.checked == 1 { "" } else { "s" }));
                        }
                        if c.unchecked > 0 {
                            what.push(format!("unchecked {}", c.unchecked));
                        }
                        if what.is_empty() {
                            what.push(format!("edited (+{} −{})", c.added, c.removed));
                        }
                        events.push((
                            c.time,
                            event_row(
                                icon,
                                format!("{} {}", c.author, what.join(", ")),
                                ago_label(now_unix() - c.time),
                                Some(format!("{} · {}", &c.hash[..7.min(c.hash.len())], c.subject)),
                                &theme,
                            ),
                        ));
                    }
                }
                Some(_) => events.push((0, div().text_xs().text_color(muted).child("No git history: the folder is not in a repository.").into_any_element())),
                None => events.push((0, div().text_xs().text_color(muted).child("Reading history…").into_any_element())),
            }
        }
        let style = md_style(cx);
        let mut comment_rows: Vec<AnyElement> = Vec::new();
        if tab != ActivityTab::History {
            for (ci, c) in d.comments.iter().enumerate() {
                comment_rows.push(
                    div()
                        .id(("comment", ci))
                        .rounded(px(8.))
                        .border_1()
                        .border_color(border)
                        .p_3()
                        .flex()
                        .flex_col()
                        .gap_1p5()
                        .child(
                            div()
                                .flex()
                                .items_center()
                                .gap_2()
                                .child(avatar(&c.author))
                                .child(div().text_sm().text_color(fg).child(c.author.clone()))
                                .when(c.ai, |d| {
                                    d.child(
                                        div()
                                            .flex()
                                            .items_center()
                                            .gap_1()
                                            .px_1p5()
                                            .rounded(px(4.))
                                            .bg(theme.blue.opacity(0.15))
                                            .text_xs()
                                            .text_color(theme.blue)
                                            .child(Icon::new(IconName::Bot).size(px(11.)))
                                            .child("AI triage"),
                                    )
                                })
                                .child(div().text_xs().text_color(muted).child(c.when.clone())),
                        )
                        .child(TextView::new(&c.body).selectable(true).style(style.clone()))
                        .into_any_element(),
                );
            }
            if d.comments.is_empty() && tab == ActivityTab::Comments {
                comment_rows.push(div().text_xs().text_color(muted).child("No comments. Skills append them under ## Comments.").into_any_element());
            }
        }
        events.sort_by_key(|(t, _)| -*t);
        div()
            .flex()
            .flex_col()
            .gap_3()
            .pt_4()
            .border_t_1()
            .border_color(border)
            .child(
                div()
                    .flex()
                    .items_center()
                    .gap_3()
                    .child(div().text_base().font_weight(FontWeight::SEMIBOLD).text_color(fg).child("Activity"))
                    .child(tabs),
            )
            .children(comment_rows)
            .child(div().flex().flex_col().gap_0p5().children(events.into_iter().map(|(_, e)| e)))
            .into_any_element()
    }
}

/// `[text](url)` → `text`.
fn link_text(s: &str) -> Option<String> {
    let a = s.find('[')?;
    let b = s[a..].find(']')? + a;
    Some(s[a + 1..b].to_string())
}

fn avatar(name: &str) -> impl IntoElement + use<> {
    div()
        .flex_none()
        .size(px(20.))
        .rounded_full()
        .bg(icons::tag_color(name))
        .flex()
        .items_center()
        .justify_center()
        .text_size(px(10.))
        .text_color(rgb(0x000000))
        .child(name.chars().next().unwrap_or('?').to_uppercase().to_string())
}

fn check_row(item: &CheckItem, t: &Theme, style: &TextViewStyle) -> AnyElement {
    let (muted, fg, accent) = (t.muted_foreground, t.foreground, t.accent);
    let done = item.done;
    // One line of text is 22px tall; the box sits in the middle of the
    // first line whatever the item's length.
    let line = px(22.);
    div()
        .flex()
        .items_start()
        .gap_3()
        .pl(px(14. + item.depth as f32 * 20.))
        .pr_4()
        .py(px(7.))
        .child(
            div().h(line).flex_none().flex().items_center().child(
                div()
                    .size(px(16.))
                    .rounded(px(4.))
                    .border_1()
                    .border_color(if done { accent } else { muted.opacity(0.6) })
                    .when(done, |d| d.bg(accent))
                    .flex()
                    .items_center()
                    .justify_center()
                    .when(done, |d| d.child(Icon::new(IconName::Check).size(px(11.)).text_color(t.background))),
            ),
        )
        .child(
            div()
                .flex_1()
                .min_w_0()
                .line_height(line)
                .text_color(if done { muted } else { fg })
                .child(TextView::markdown(("chk-text", item.line), item.text.clone()).style(style.clone())),
        )
        .into_any_element()
}

fn event_row(icon: Icon, text: String, when: String, sub: Option<String>, t: &Theme) -> AnyElement {
    div()
        .flex()
        .items_start()
        .gap_2p5()
        .py(px(6.))
        .child(div().flex_none().pt(px(2.)).child(icon.size(px(15.))))
        .child(
            div()
                .flex_1()
                .min_w_0()
                .flex()
                .flex_col()
                .gap_0p5()
                .child(
                    div()
                        .flex()
                        .flex_wrap()
                        .gap_x_2()
                        .text_sm()
                        .child(div().text_color(t.foreground).child(text))
                        .child(div().text_color(t.muted_foreground).child(when)),
                )
                .when_some(sub, |d, s| {
                    d.child(div().truncate().text_xs().font_family(crate::settings::mono_font()).text_color(t.muted_foreground).child(s))
                }),
        )
        .into_any_element()
}

fn progress(done: usize, total: usize, t: &Theme, light: bool) -> impl IntoElement + use<> {
    let frac = if total == 0 { 0. } else { done as f32 / total as f32 };
    let c = if total > 0 && done == total { icons::status_color(Category::Done, light) } else { t.accent };
    div()
        .flex()
        .items_center()
        .gap_2()
        .child(
            div()
                .w(px(90.))
                .flex_none()
                .h(px(5.))
                .rounded_full()
                .bg(t.muted_foreground.opacity(0.18))
                .child(div().h_full().rounded_full().bg(c).w(relative(frac))),
        )
        .child(
            div()
                .flex_none()
                .text_xs()
                .text_color(t.muted_foreground)
                .child(format!("{done}/{total} · {:.0}%", frac * 100.)),
        )
}

/// A titled group of the side panel (Linear's Properties / Labels boxes).
/// Its title folds it; the state is kept per board.
fn section_box(title: &str, inner: AnyElement, open: bool, t: &Theme) -> AnyElement {
    let key = format!("detail:{title}");
    div()
        .flex()
        .flex_col()
        .gap_2()
        .p_3()
        .rounded(px(10.))
        .border_1()
        .border_color(t.border)
        .min_w_0()
        .child(
            div()
                .id(SharedString::from(key.clone()))
                .flex()
                .items_center()
                .gap_1()
                .cursor_pointer()
                .text_xs()
                .font_weight(FontWeight::MEDIUM)
                .text_color(t.muted_foreground)
                .hover(|d| d.text_color(t.foreground))
                .child(title.to_string())
                .child(
                    Icon::new(if open { IconName::ChevronDown } else { IconName::ChevronRight })
                        .size(px(11.))
                        .text_color(t.muted_foreground.opacity(0.6)),
                )
                .on_click(move |_, _, cx| {
                    let key = key.clone();
                    crate::app::with_app(cx, |this, cx| {
                        this.toggle_fold(&key);
                        cx.notify();
                    })
                }),
        )
        .when(open, |d| d.child(inner))
        .into_any_element()
}

fn tip_text(text: String) -> impl Fn(&mut Window, &mut App) -> AnyView {
    move |window, cx| gpui_kit::component::tooltip::Tooltip::new(text.clone()).max_w(px(360.)).build(window, cx)
}
